name: Deploy to GitHub Pages

on:
  workflow_dispatch:

# Grant permissions to allow the deployment action to publish to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "26"
      - name: Build site with Makefile
        run: make pub
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v7
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
